Merged /chain/height and /chain/score into /chain/info and included finalization information
nemtech/symbol-openapi pull request #196
Opened 2020-08-25 06:13 UTC by Vektrat

as discussed here: https://github.com/nemtech/catapult-rest/issues/461

2020-08-25 07:21 UTC, Vektrat commented
@AnthonyLaw

2020-08-25 08:20 UTC, AnthonyLaw commented
@Vektrat It look good for me 👍

2020-09-10 15:04 UTC, Vektrat commented
please review again, i left the specific types (FinalizationPoint/Epoch) because they are reused and serve as a better documentation, check if the type `integer` is fine, or you prefer to specify it to uint32 somehow

2020-09-10 15:07 UTC, rg911 requested changes

2020-09-10 15:07 UTC, rg911 commented on spec/schemas/_index.yml
>  FinalizationPoint:
old property still here

2020-09-11 17:21 UTC, rg911 submitted a review, later dismissed

2020-09-12 10:12 UTC, fboucquez commented on spec/core/chain/schemas/ChainInfoDTO.yml
> +  - finalizedHeight
is `finalizedHeight` duplicated value? User can get it from `latestFinalizedBlock.height`

2020-09-12 10:58 UTC, fboucquez commented on spec/core/chain/schemas/FinalizedBlockDTO.yml
> +type: object
Is this the same schema than the finalized block WS payload? We should move this file to the top level schema folder

2020-09-14 13:32 UTC, fboucquez commented on spec/core/chain/schemas/ChainInfoDTO.yml
> +  - finalizedHeight
@Vektrat

2020-09-14 13:45 UTC, fboucquez approved these changes

2020-09-14 15:10 UTC, merged