Added from/to height query filters to the transaction search endpoints
nemtech/symbol-openapi pull request #205
Opened 2020-09-09 08:42 UTC by Vektrat

Closes https://github.com/nemtech/catapult-rest/issues/469

2020-09-09 08:59 UTC, Vektrat commented
note that this aims to allow the clients to be able to filter transactions by height (period) range which is what the architecture offers

as you know, the chain does not contain explicit real world timestamp data, thus if user experience needs to be improved, it is in the hands of the SDK/clients to offer a way to convert height to timestamp (probably involving timestamp fields and nemesis block creation data)

2020-09-09 09:41 UTC, segfaultxavi requested changes

2020-09-09 09:41 UTC, segfaultxavi commented on spec/parameters/query/fromHeight.yml
> +description: Filter from block height.
The description should say if the block with that exact same height is included or not (inclusive or exclusive filter).

Also, the word "filter" can be a bit ambiguous. I would clarify it adding something like `Only blocks with height greater than this one are returned.`.

2020-09-09 09:41 UTC, segfaultxavi commented on spec/parameters/query/toHeight.yml
> +description: Filter up to block height.
Same comment as above.

2020-09-14 15:45 UTC, martinayora approved these changes

2020-09-14 16:14 UTC, martinayora approved these changes

2020-09-15 15:37 UTC, segfaultxavi approved these changes
My concerns have been addressed.

2020-09-15 19:01 UTC, Vektrat commented
this is ready but waiting for fernando to give green light (he asked us to wait to merge this because his schemas would be regenerated or something)

2020-09-17 14:10 UTC, merged