Added transactions transferMosaicId filter
nemtech/symbol-openapi pull request #225
Opened 2020-09-25 10:45 UTC by martinayora

Fixes #224.

2020-09-25 11:00 UTC, segfaultxavi requested changes
Minor nitpick :)

2020-09-25 11:00 UTC, segfaultxavi commented on spec/parameters/query/transferMosaicId.yml
> +description: Filters transactions where a specific mosaicId is involved.
```suggestion
description: Filters transactions involving a specific ``mosaicId``.
```

2020-09-28 17:33 UTC, Vektrat commented on spec/parameters/query/transferMosaicId.yml
> +description: Filters transactions where a specific mosaicId is involved.
@martinayora

2020-09-29 07:07 UTC, Vektrat approved these changes

2020-09-29 07:28 UTC, segfaultxavi approved these changes

2020-09-29 07:34 UTC, merged