Updated version and CHANGELOG.md
nemtech/symbol-openapi pull request #254
Opened 2020-12-03 16:13 UTC by fboucquez

2020-12-03 16:19 UTC, rg911 requested changes

2020-12-03 16:19 UTC, rg911 commented on CHANGELOG.md
>  - Allowing secret lock searches without filters.
Updated finalization proof schema added optional signatureSchema

2020-12-03 21:01 UTC, segfaultxavi submitted a review, later dismissed
I see no language issues.

2020-12-04 19:02 UTC, rg911 approved these changes

2020-12-04 23:55 UTC, merged